CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role ENUM('admin','recruiter','candidate') DEFAULT 'candidate',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS jobs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  company VARCHAR(255) NOT NULL,
  location VARCHAR(255),
  salary VARCHAR(100),
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE applications (
  id INT PRIMARY KEY AUTO_INCREMENT,
  candidate_name VARCHAR(100),
  job_title VARCHAR(100),
  status VARCHAR(20),
  source VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  recruiter_id INT,
  package_lpa FLOAT,
  joining_date DATE,
  remote BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS companies (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  industry VARCHAR(255),
  employees INT,
  website VARCHAR(255),
  description TEXT,
  logo VARCHAR(500),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS analytics (
  id INT AUTO_INCREMENT PRIMARY KEY,
  event VARCHAR(255) NOT NULL,
  user_id INT,
  metadata JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE resumes (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100),
  title VARCHAR(100),
  summary TEXT,
  skills TEXT,
  experience TEXT,
  education TEXT,
  certifications TEXT,
  projects TEXT,
  email VARCHAR(100),
  phone VARCHAR(20),
  location VARCHAR(100),
  links TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE mock_interviews (
  id INT PRIMARY KEY AUTO_INCREMENT,
  role VARCHAR(100),
  difficulty VARCHAR(20),
  answers JSON NULL,
  score INT DEFAULT 0,
  feedback TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS salary_reports (
  id INT AUTO_INCREMENT PRIMARY KEY,
  role VARCHAR(100) NOT NULL,
  experience VARCHAR(50) NOT NULL,
  location VARCHAR(100) NOT NULL,
  min_lpa INT NOT NULL,
  max_lpa INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admin_settings (
  id INT PRIMARY KEY AUTO_INCREMENT,
  setting_key VARCHAR(100) UNIQUE NOT NULL,
  setting_value BOOLEAN NOT NULL
);

CREATE TABLE admin_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  log TEXT NOT NULL,
  time VARCHAR(100) NOT NULL
);
